# Generated by Django 6.0.5 on 2026-05-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personaje', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='personajes/')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('clase', models.CharField(choices=[('Heroe', 'Héroe'), ('Villano', 'Villano'), ('Monstruo', 'Monstruo'), ('Civil', 'Civil')], max_length=30)),
                ('rango', models.CharField(max_length=50)),
                ('afiliacion', models.CharField(max_length=100)),
                ('nivel_poder', models.IntegerField()),
                ('edad', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
