# Generated by Django 6.0.5 on 2026-05-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='rango',
        ),
        migrations.AddField(
            model_name='personaje',
            name='clase_heroe',
            field=models.CharField(blank=True, choices=[('Clase S', 'Clase S'), ('Clase A', 'Clase A'), ('Clase B', 'Clase B'), ('Clase C', 'Clase C'), ('Sin clase', 'Sin clase')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='nivel_amenaza',
            field=models.CharField(blank=True, choices=[('Lobo', 'Lobo'), ('Tigre', 'Tigre'), ('Demonio', 'Demonio'), ('Dragón', 'Dragón'), ('Dios', 'Dios')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='rango_heroe',
            field=models.CharField(blank=True, choices=[('Rango 1', 'Rango 1'), ('Rango 2', 'Rango 2'), ('Rango 3', 'Rango 3'), ('Rango 4', 'Rango 4'), ('Rango 5', 'Rango 5'), ('Sin rango', 'Sin rango')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='tipo',
            field=models.CharField(choices=[('Heroe', 'Héroe'), ('Kaijin', 'Kaijin'), ('Civil', 'Civil')], default='Heroe', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personaje',
            name='afiliacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
