# Generated by Django 6.0.5 on 2026-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_personaje_clase_remove_personaje_rango_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='rango_heroe',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
